services:
    matthimatiker_opcache.data_collector:
        class: Matthimatiker\OpcacheBundle\DataCollector\ByteCodeCacheDataCollector
        arguments: []
        tags:
            - { name: "data_collector", template: "MatthimatikerOpcacheBundle:DataCollector:ByteCodeCache", id: "matthimatiker_opcache.byte_code_cache" }
