language: php

php:
    - '7.0'
    - '7.1'

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
