language: php

php:
    - '7.0'
    - '7.1'

before_script:
    - travis_retry curl -s http://getcomposer.org/installer | php
    - travis_retry php composer.phar install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
